version: "3.9"

services:
  app:
    build: .
    container_name: hostel_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  mongo:
    image: mongo:7
    container_name: hostel_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hostel_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
